[project]
name = "ha-cez-distribution-hdo"
version = "0.3.0-beta2"
description = "HomeAssistant integration for CEZ Distribution HDO."
authors = [
    { name = "pokornyIt", email = "8665714+pokornyIt@users.noreply.github.com" },
]
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = ["homeassistant>=2025.12.0", "cez-distribution-hdo ~=0.2.0"]

[dependency-groups]
dev = ["homeassistant-stubs>=2025.12.0", "ruff ~=0.14.0", "pyright ~=1.1"]

[tool.pyright]
reportIncompatibleVariableOverride = "none"
venvPath = "."
venv = ".venv"
